version: 2.1
# orbs:
#  ruby: circleci/ruby@0.1.2

executors:
  ruby-test-executor:
    docker:
      - image: cimg/ruby:2.6.6

jobs:
  build:
    executor: ruby-test-executor
    environment:
      - BUNDLE_PATH: vendor/bundle
      - RAILS_ENV: production
    steps:
      - checkout
      - run:
          name: Which ruby?
          command: ruby -v

workflows:
  version: 2.1
  test:
    jobs:
      - build:
          filters:
            branches:
              only: /^develop/
